config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  get "welcome", to: "pages#welcome", as: "welcome"
  get "useroptions", to: "pages#useroptions"
  get "map", to: "maps#index"
  get "party", to: "parties#new"
  get "homeparty", to: "parties#new_homeparty"
  get "feed", to: "feed#index"

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  post "feed", to: "posts#create", as: "new_post"
  get "feeds", to: "posts#index", as: "posts"

  resources :parties, only: [:new, :create] do
    resources :participants, only: %i[new create]
  end
  resources :invitations, only: [:new, :create]
  resources :chatrooms, only: [:show, :index] do
    resources :messages, only: :create
  end


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  belongs_to :party # chatroom.party => Party.find(chatroom.party_id)
  has_many :messages
  has_many :participants
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  def index
    participations = Participant.where(user: current_user)
    @chatrooms = participations.map { |participation| participation.party.chatroom }
    @post = Post.new
  end

  def show
    @chatroom = Chatroom.find(params[:id])
    @message = Message.new
  end
end

app/views/chatrooms/index.html.erb
<h1 class="text-center">Chats</h1>
<ul>
  <% @chatrooms.each do |chatroom| %>
    <div class="notification">
      <div class="notification-content">
        <li>
          <p><small><%= chatroom.party.start_time.strftime("%b %e, %l:%M %p") %></small></p>
          <h2><%= link_to chatroom.name, chatroom_path(chatroom), class:"text-decoration-none", id:"h2-chatroom" %></h2>
          <p><small><%= chatroom.party.address %></small></p>

          <div class="border-top">
            <% if chatroom.messages != [] %>
              <p id="text-alignment"><%= chatroom.messages.last.participant.user.email%>: <%= chatroom.messages[-1].content %></p>
            <% else %>
              <p id="text-alignment">No messages</p>
            <% end %>
          </div>
        </li>
      </div>
        <% if chatroom.party.user.photo.attached? %>
          <%= cl_image_tag chatroom.party.user.photo.key, crop: :fill, class: "rounded-circle avatar-large",
          aria: {expanded: false, haspopup: true} %>
        <% else %>
          <%= image_tag 'current_user.jpg', class: "rounded-circle avatar-large" %>
        <% end %>
    </div>
  <% end %>
</ul>

app/views/chatrooms/show.html.erb
<div class=" chatroom" data-controller="chatroom-subscription" data-chatroom-subscription-chatroom-id-value="<%= @chatroom.id %>" data-chatroom-subscription-current-user-id-value="<%= current_user.id %>">

  <h1>
    <%= link_to "<", chatrooms_path, class:"text-decoration-none white-btn" %>
    <%= @chatroom.name %>
  </h1>

  <div class="messages style-chat" data-chatroom-subscription-target="messages">
    <% @chatroom.messages.each do |message| %>
      <div id="message-<%= message.id %>" class="d-flex w-100 mt-2 <%= message.user == current_user ? "justify-content-end" : "justify-content-start" %>">
        <div class=<%= message.user == current_user ? "msg-blue" : "msg-white" %>>
          <%= render "messages/message", message: message %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="bottom-form">
  </div>

  <%= form_for [@chatroom, @message], html: { data: { action: "turbo:submit-end->chatroom-subscription#resetForm" },
    class: "message-form border-0" } do |f|
  %>
    <%= f.text_field :content,
      label: false,
      class: "msg-input border-0",
      placeholder: "        Type message..."
    %>
    <%= button_tag type: "submit", class: "rounded-circle submit" do %>
      <i class="fa-regular fa-paper-plane fa-xl"></i>
    <% end %>
  <% end %>
</div>