config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  get "welcome", to: "pages#welcome", as: "welcome"
  get "useroptions", to: "pages#useroptions"
  get "map", to: "maps#index"
  get "party", to: "parties#new"
  get "homeparty", to: "parties#new_homeparty"
  get "feed", to: "feed#index"

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  post "feed", to: "posts#create", as: "new_post"
  get "feeds", to: "posts#index", as: "posts"

  resources :parties, only: [:new, :create] do
    resources :participants, only: %i[new create]
  end
  resources :invitations, only: [:new, :create]
  resources :chatrooms, only: [:show, :index] do
    resources :messages, only: :create
  end


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/shared/_bottom_nav.html.erb
<% if current_user %>
  <div class="bottom_nav w-100" data-controller="toggle">
    <%= link_to "", root_path, class: "fa-solid fa-house fa-sm item_left item" %>
    <%= link_to "", posts_path, class: "fa-regular fa-image fa-sm item_right item" %>
    <span class="btn-plus" data-action="click->toggle#toggle"><i class="fa-solid fa-plus fa-sm plus-icon"></i></span>
    <%= link_to "", chatrooms_path, class:"fa-regular fa-comments fa-sm item_left item text-decoration-none" %>
    <span>
      <%= link_to useroptions_path do %>
        <% if current_user.photo.attached? %>
          <a class="dropup" data-bs-toggle="dropdown" aria-expanded="false">
            <%= cl_image_tag current_user.photo.key, height: 38, width: 38, crop: :fill, class: "rounded-circle"%>
            <ul class="dropdown-menu d-flex flex-column justify-content-center align-item-center">
              <%= link_to "Logout", destroy_user_session_path, class: "link-danger text-decoration-none", data: {turbo_method: :delete} %>
            </ul>
          </a>
        <% else %>
          <%= image_tag 'current_user.jpg',  height: 38, width: 38, class: "rounded-circle" %>
        <% end %>
      <% end %>
    </span>

    <div class="popup hide-popup" data-toggle-target="popup">
      <div class="close-btn">
        <button type="button" class="btn-close btn-close-white" aria-label="Close" data-action="click->toggle#toggle"></button>
      </div>
    <h2 class="h2"><strong>Options</strong> </h2>
    <%= link_to"Create Party", homeparty_path, class:"select-location"   %>
    <p style="margin-top: 16px; opacity: 50%">― or ―</p>
    <%= form_for @post, url: new_post_path do |f| %>
    <p class="add-post" onClick="this.nextElementSibling.nextElementSibling.click()">Create Post</p>
    <%= f.file_field :photos, as: :file, multiple: true, onchange: "this.form.submit()", class: "d-none" %>
    <% end %>
  </div>
<% else %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <p><strong>Hey Man!<strong>You have to <%= link_to "Sign Up", new_user_registration_path, class: "link-warning"%> to continue</p>
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon w-100">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "Hangover_pic.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="fa-solid fa-bars burger"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav p-0">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Create a new location", "#", class: "nav-link text-white text-center" %>
            <%= link_to "Add friend", new_invitation_path, class: "nav-link text-white text-center" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link text-white" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>