config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  get "welcome", to: "pages#welcome", as: "welcome"
  get "useroptions", to: "pages#useroptions"
  get "map", to: "maps#index"
  get "party", to: "parties#new"
  get "homeparty", to: "parties#new_homeparty"
  get "feed", to: "feed#index"

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  post "feed", to: "posts#create", as: "new_post"
  get "feeds", to: "posts#index", as: "posts"

  resources :parties, only: [:new, :create] do
    resources :participants, only: %i[new create]
  end
  resources :invitations, only: [:new, :create]
  resources :chatrooms, only: [:show, :index] do
    resources :messages, only: :create
  end


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hangover</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <link rel="manifest" href="<%= asset_path 'manifest.json' %>">
    <%= render 'shared/ios_pwa_links' %>

    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>">
    <meta property="og:type" content="website">
    <meta property="og:url" content="<%= request.original_url %>">
    <meta property="og:image" content="<%= meta_image %>">
    <meta property="og:description" content="<%= meta_description %>">
    <meta property="og:site_name" content="<%= meta_title %>">

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">

  </head>
  <body class=<%= "bg-dark-grey" if controller_path == "participants"%>>
    <%= render "shared/navbar" unless (controller_name == "chatrooms" && action_name == "show") || (controller_name == "participants") || (controller_name == "pages" && action_name == "welcome")%>
    <%= render "shared/flashes" %>
    <%= yield %>

      <%= render "shared/bottom_nav" unless (controller_name == "parties") || (controller_name == "invitations") || (controller_name == "chatrooms" && action_name == "show") || (controller_name == "participants") || (controller_name == "pages" && action_name == "welcome") %>

  </body>
</html>